import React, { useContext } from "react";
import { LanguageContext } from "./LanguageContext";

function WelcomeMessage() {
  const { language } = useContext(LanguageContext);
  const messages = {
    ENG: "In today's interconnected world, understanding and embracing cultural diversity is more important than ever. It enables us to build stronger communities and foster mutual respect among different peoples. By acknowledging and celebrating our differences, we pave the way for a more inclusive and equitable society. Technology plays a pivotal role in bridging gaps between cultures. Through the power of the internet and digital communication tools, we have the opportunity to learn from and connect with people across the globe. This connectivity not only enhances our knowledge but also enriches our lives by exposing us to a wide array of perspectives and experiences.",
    GER: "In der heutigen vernetzten Welt ist es wichtiger denn je, kulturelle Vielfalt zu verstehen und zu umarmen. Dies ermöglicht es uns, stärkere Gemeinschaften aufzubauen und gegenseitigen Respekt zwischen verschiedenen Völkern zu fördern. Indem wir unsere Unterschiede anerkennen und feiern, bereiten wir den Weg für eine inklusivere und gerechtere Gesellschaft. Technologie spielt eine entscheidende Rolle dabei, Lücken zwischen Kulturen zu überbrücken. Durch die Kraft des Internets und digitaler Kommunikationsmittel haben wir die Möglichkeit, von Menschen auf der ganzen Welt zu lernen und mit ihnen in Verbindung zu treten. Diese Vernetzung verbessert nicht nur unser Wissen, sondern bereichert auch unser Leben, indem sie uns eine Vielzahl von Perspektiven und Erfahrungen bietet.",
    TR: "Günümüzün birbirine bağlı dünyasında, kültürel çeşitliliği anlamak ve benimsemek her zamankinden daha önemli. Bu, daha güçlü topluluklar inşa etmemize ve farklı halklar arasında karşılıklı saygıyı teşvik etmemize olanak tanır. Farklılıklarımızı kabul ederek ve kutlayarak, daha kapsayıcı ve adil bir toplum için yolu açarız. Teknoloji, kültürler arası boşlukları kapatmada önemli bir rol oynar. İnternetin ve dijital iletişim araçlarının gücü sayesinde, dünya genelindeki insanlardan öğrenme ve onlarla bağlantı kurma fırsatına sahibiz. Bu bağlantı, bilgimizi artırmakla kalmaz, aynı zamanda bizi geniş bir perspektif ve deneyim yelpazesiyle tanıştırarak hayatlarımızı zenginleştirir.",
    AR: "في عالم اليوم المترابط، أصبح فهم واحتضان التنوع الثقافي أكثر أهمية من أي وقت مضى. يمكننا ذلك من بناء مجتمعات أقوى وتعزيز الاحترام المتبادل بين الشعوب المختلفة. من خلال الاعتراف والاحتفال بالاختلافات لدينا، نمهد الطريق لمجتمع أكثر شمولية وعدالة.    تلعب التكنولوجيا دورًا رئيسيًا في جسر الفجوات بين الثقافات. من خلال قوة الإنترنت وأدوات الاتصال الرقمية، لدينا الفرصة للتعلم من الناس في جميع أنحاء العالم والتواصل معهم. هذه الاتصالات لا تعزز معرفتنا فحسب، بل تثري حياتنا أيضًا من خلال تعريضنا لمجموعة واسعة من المنظورات والتجارب.",
    SP: "En el mundo interconectado de hoy, comprender y abrazar la diversidad cultural es más importante que nunca. Esto nos permite construir comunidades más fuertes y fomentar el respeto mutuo entre diferentes pueblos. Al reconocer y celebrar nuestras diferencias, allanamos el camino para una sociedad más inclusiva y justa. La tecnología juega un papel fundamental en el cierre de brechas entre culturas. A través del poder de internet y las herramientas de comunicación digital, tenemos la oportunidad de aprender de y conectar con personas de todo el mundo. Esta conectividad no solo mejora nuestro conocimiento, sino que también enriquece nuestras vidas al exponernos a una amplia gama de perspectivas y experiencias.",
  };

  return <p>{messages[language]}</p>;
}

export default WelcomeMessage;
